spring:
  application:
    name: todo

todoapp:
  site:
    author: Jun Park
    description: What's up
  data:
    initialize: true
  feature-toggles:
    auth: true
    onlineUsersCounter: false

logging:
  level:
    web: trace
    '[todoapp]': debug
    sql: debug

server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      charset: UTF-8
      force: true
